site_name: DeciBull
nav:
    - Home: index.md
    - About DeciBull: About.md
    - How it works: How.md
    - See DeciBull in Action: Examples.md
    - Team: Team.md
feature:
    tabs: true
theme:
    name: material
    logo: img/logo_large.png
    features: 
        - navigation.tabs

extra_css:
    - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - toc:
      toc_depth : "1-1"

