site_name: DeciBull
nav:
    - Home: 
        - index.md
    - About:
        - About.md
        - Motivation.md
    - How it works:
        - AudioSuperResolution.md
        - GAN.md
        - Evaluation.md
    - See DeciBull in Action:
        - Examples.md
    - Team:
        - Team.md
        - Contact.md
feature:
    tabs: true
hide:
    - navigation # Hide navigation
theme:
    name: material
    logo: img/logo_large.png
    features: 
        - navigation.tabs

extra_css:
    - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - meta
  - toc:
      toc_depth : "1-1"

