site_name: Decibull
nav:
    - Home: index.md
    - About: About.md
    - How it works: How.md
    - Examples: Examples.md
    - Team: Team.md
    - Contact Us: Contact.md
theme:
    name: material
